version: '3'

services:

  db_event_management_commands:
    image: postgres:13
    container_name: db_em_commands
    environment:
      POSTGRES_DB: db_event_management_commands
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: emCommands
    networks:
      - em_net

    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres -d db_event_management_commands"]
        interval: 5s
        timeout: 10s
        retries: 5

  event_management_commands:
    build:
      context: ./core_functionalities/event_management_commands
    container_name: event_management_commands_container
    ports:
      - "3001:3001"
    depends_on:
      - db_event_management_commands
    environment:
      DATABASE_URL: postgresql://postgres:emCommands@db_event_management_commands:5432/db_event_management_commands
    networks:
      - em_net

  db_event_management_queries:
    image: postgres:13
    container_name: db_em_queries
    environment:
      POSTGRES_DB: db_event_management_queries
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: emQueries
    networks:
      - em_net

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d db_event_management_queries"]
      interval: 5s
      timeout: 10s
      retries: 5

  event_management_queries:
    build:
      context: ./core_functionalities/event_management_queries
    container_name: event_management_queries_container
    ports:
      - "3002:3002"
    depends_on:
      - db_event_management_queries
    environment:
      DATABASE_URL: postgresql://postgres:emQueries@db_event_management_queries:5432/db_event_management_queries
    networks:
      - em_net

  db_training_management:
    image: postgres:13
    container_name: db_tmq
    environment:
      POSTGRES_DB: db_training_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tmqUnoDos
    networks:
      - tmq_net

    healthcheck:
          test: ["CMD-SHELL", "pg_isready -U postgres -d db_training_management"]
          interval: 5s
          timeout: 10s
          retries: 5

  training_management_queries:
    build:
      context: ./core_functionalities/training_management_queries
    container_name: training_management_queries_container
    ports:
      - "3000:3000"
    depends_on:
      db_training_management:
        condition: service_healthy

    environment:
      DATABASE_URL: postgresql://postgres:tmqUnoDos@db_training_management:5432/db_training_management
    networks:
      - tmq_net

networks:
  # app_net:
  tmq_net:
  em_net:
    driver: bridge